### ISSUE TITLE
Receiving FrozenError on core:log_revision

### ISSUE THREAD

**Issue by mikegabriel** [mattbrictson/tomo#454]
Hello,

I am just in the process of migrating to tomo from capistrano and came across one issue at the end of my deploy.

My environment is running ruby 3.3.4 and when `core:log_revision` is ran, it fails with a `FrozenError`.  Here is the stack trace.

```
tomo run core:log_revision          
tomo run v1.19.0
• core:log_revision
/Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/plugin/core/tasks.rb:62:in `log_revision': can't modify frozen String: "" (FrozenError)
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/task_runner.rb:29:in `call'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/task_runner.rb:29:in `block in run'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/current.rb:20:in `with'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/task_runner.rb:27:in `run'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/host_execution_step.rb:28:in `block (2 levels) in execute'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/host_execution_step.rb:23:in `each'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/host_execution_step.rb:23:in `block in execute'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/inline_thread_pool.rb:7:in `post'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/host_execution_step.rb:22:in `execute'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/execution_plan.rb:38:in `block (3 levels) in execute'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/execution_plan.rb:37:in `each'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/execution_plan.rb:37:in `block (2 levels) in execute'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/execution_plan.rb:36:in `each'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/execution_plan.rb:36:in `block in execute'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/execution_plan.rb:71:in `open_connections'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime/execution_plan.rb:35:in `execute'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/runtime.rb:55:in `run!'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/commands/run.rb:57:in `call'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/cli/command.rb:26:in `parse'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/lib/tomo/cli.rb:44:in `call'
	from /Users/mike/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/tomo-1.19.0/exe/tomo:4:in `<top (required)>'
	from /Users/mike/.rbenv/versions/3.3.4/bin/tomo:25:in `load'
	from /Users/mike/.rbenv/versions/3.3.4/bin/tomo:25:in `<main>'
```

**Comment by mikegabriel** [comment]
Ah, never mind.

I see from looking at the source files that the remote.release hash values are only set in the previous command `git:create_release`.

Running this task on its own will fail, I will close this issue now.
